export default [
    {id: '1',  tarefa: 'Fazer 01', done:true },
    {id: '2',  tarefa: 'Fazer 02', done:false},
    {id: '3',  tarefa: 'Fazer 03', done:false},
    {id: '4',  tarefa: 'Fazer 04', done:false},
    {id: '5',  tarefa: 'Fazer 05', done:false},
    {id: '6',  tarefa: 'Fazer 06', done:false},
    {id: '7',  tarefa: 'Fazer 07', done:false},
    {id: '8',  tarefa: 'Fazer 08', done:false},
    {id: '9',  tarefa: 'Fazer 09', done:false},
    {id: '10', tarefa: 'Fazer 10', done:false},
    {id: '11', tarefa: 'Fazer 11', done:false},
    {id: '12', tarefa: 'Fazer 12', done:false},
    {id: '13', tarefa: 'Fazer 13', done:false},
    {id: '14', tarefa: 'Fazer 14', done:false},
    {id: '15', tarefa: 'Fazer 15', done:false},
    {id: '16', tarefa: 'Fazer 16', done:false},
    {id: '17', tarefa: 'Fazer 17', done:false},
    {id: '18', tarefa: 'Fazer 18', done:false},
    {id: '19', tarefa: 'Fazer 19', done:false},
    {id: '20', tarefa: 'Fazer 20', done:false},
    {id: '21', tarefa: 'Fazer 21', done:false},
    {id: '22', tarefa: 'Fazer 22', done:false},
    {id: '23', tarefa: 'Fazer 23', done:false}
];